//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelBasvuru.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BasvuruEntities3 : DbContext
    {
        public BasvuruEntities3()
            : base("name=BasvuruEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ILCELER> ILCELERs { get; set; }
        public virtual DbSet<ILLER> ILLERs { get; set; }
        public virtual DbSet<PERSONEL> PERSONELs { get; set; }
        public virtual DbSet<PERSONELISBASVURULARI> PERSONELISBASVURULARIs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
