//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelBasvuru.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONEL
    {
        public int ID { get; set; }
        public string ADSOYAD { get; set; }
        public Nullable<int> ILID { get; set; }
        public Nullable<int> ILCEID { get; set; }
        public string CINSIYET { get; set; }
        public Nullable<System.DateTime> DOGUMTARIHI { get; set; }
        public string ACIKLAMA { get; set; }
    }
}
